# Generated by Django 3.0 on 2020-12-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enroled',
            field=models.BooleanField(default=False),
        ),
    ]
