# Generated by Django 3.0 on 2020-12-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_enroled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allowed_membership',
        ),
    ]
