# Generated by Django 3.0 on 2020-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201223_1522'),
        ('core', '0005_remove_course_allowed_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_membership',
            field=models.ManyToManyField(default='free', to='membership.Membership'),
        ),
    ]
