# Generated by Django 3.0 on 2020-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'free'), ('Professional', 'pro'), ('Enterprise', 'ent')], default='free', max_length=30),
        ),
    ]
