# Generated by Django 3.0 on 2020-11-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeTemplate',
            new_name='Snippet',
        ),
    ]
