# Generated by Django 3.0 on 2020-12-19 15:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This is a rich text field'),
            preserve_default=False,
        ),
    ]
