# Generated by Django 3.0 on 2020-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_templates', '0002_auto_20201120_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=23.23, max_digits=6),
            preserve_default=False,
        ),
    ]
