# Generated by Django 3.0 on 2020-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_templates', '0003_snippet_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(default='new'),
            preserve_default=False,
        ),
    ]
