# Generated by Django 3.0 on 2020-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='articles')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='this is the description'),
            preserve_default=False,
        ),
    ]
